// flow-typed signature: 8a3c58c32336c42aae5ecb9b2ff26af4
// flow-typed version: <<STUB>>/@all-user/ok-patterns-lines_v0.0.3/flow_v0.40.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@all-user/ok-patterns-lines'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module '@all-user/ok-patterns-lines' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '@all-user/ok-patterns-lines/lib/index' {
  declare module.exports: any;
}

declare module '@all-user/ok-patterns-lines/src/js/index' {
  declare module.exports: any;
}

// Filename aliases
declare module '@all-user/ok-patterns-lines/index' {
  declare module.exports: $Exports<'@all-user/ok-patterns-lines'>;
}
declare module '@all-user/ok-patterns-lines/index.js' {
  declare module.exports: $Exports<'@all-user/ok-patterns-lines'>;
}
declare module '@all-user/ok-patterns-lines/lib/index.js' {
  declare module.exports: $Exports<'@all-user/ok-patterns-lines/lib/index'>;
}
declare module '@all-user/ok-patterns-lines/src/js/index.js' {
  declare module.exports: $Exports<'@all-user/ok-patterns-lines/src/js/index'>;
}
